// demo-react/components/DynamicDemo.tsx
import { useState, useRef, useEffect } from 'react';
import { useCardAnimation } from '../../src/react/index.ts';

interface Card {
	id: number;
	title: string;
	color: string;
}

const COLORS = ['#ef4444', '#f97316', '#eab308', '#22c55e', '#3b82f6', '#a855f7', '#ec4899', '#14b8a6'];
const LABELS = ['Alpha', 'Beta', 'Gamma', 'Delta', 'Epsilon', 'Zeta', 'Eta', 'Theta'];
const MAX_CARDS = 12;

let nextId = 5;

function newCard(): Card {
	const idx = nextId % COLORS.length;
	return { id: nextId++, title: `Карточка ${LABELS[idx]}`, color: COLORS[idx] };
}

const INITIAL_CARDS: Card[] = [
	{ id: 1, title: 'Карточка Alpha', color: COLORS[0] },
	{ id: 2, title: 'Карточка Beta', color: COLORS[1] },
	{ id: 3, title: 'Карточка Gamma', color: COLORS[2] },
	{ id: 4, title: 'Карточка Delta', color: COLORS[3] },
];

export default function DynamicDemo() {
	const [cards, setCards] = useState<Card[]>(INITIAL_CARDS);

	const cardRefs = useRef<(HTMLElement | null)[]>([]);
	const shouldAnimate = useRef(false);

	const { snapshot, animateMove, isAnimating } = useCardAnimation({ duration: 400, stagger: 25 });

	useEffect(() => {
		if (!shouldAnimate.current) return;
		shouldAnimate.current = false;
		void animateMove(cardRefs.current.filter((el): el is HTMLElement => el !== null));
	}, [cards, animateMove]);

	const triggerChange = (updater: (prev: Card[]) => Card[]) => {
		snapshot(cardRefs.current.filter((el): el is HTMLElement => el !== null));
		shouldAnimate.current = true;
		setCards(updater);
	};

	const addStart = () => triggerChange(prev => [newCard(), ...prev]);
	const addEnd = () => triggerChange(prev => [...prev, newCard()]);
	const addMiddle = () => triggerChange(prev => {
		const mid = Math.floor(prev.length / 2);
		return [...prev.slice(0, mid), newCard(), ...prev.slice(mid)];
	});
	const removeFirst = () => triggerChange(prev => prev.slice(1));
	const removeLast = () => triggerChange(prev => prev.slice(0, -1));

	const full = cards.length >= MAX_CARDS;
	const empty = cards.length === 0;

	return (
		<>
			<div className="dynamic-actions">
				<button className="btn-action" onClick={addStart} disabled={isAnimating || full}>+ в начало</button>
				<button className="btn-action" onClick={addEnd} disabled={isAnimating || full}>+ в конец</button>
				<button className="btn-action" onClick={addMiddle} disabled={isAnimating || full}>+ в середину</button>
				<button className="btn-action" onClick={removeFirst} disabled={isAnimating || empty}>− первую</button>
				<button className="btn-action" onClick={removeLast} disabled={isAnimating || empty}>− последнюю</button>
				<span className="card-counter">{cards.length} / {MAX_CARDS} карточек</span>
			</div>

			<div className="card-grid">
				{cards.map((card, i) => (
					<div
						key={card.id}
						ref={el => { cardRefs.current[i] = el; }}
						className="card"
						style={{ '--card-color': card.color } as React.CSSProperties}
					>
						<span className="card__title">{card.title}</span>
						<span className="card__id">#{card.id}</span>
					</div>
				))}
			</div>
		</>
	);
}

// demo-vue/components/DynamicDemo.vue
<template>
  <div class="dynamic-actions">
    <button class="btn-action" :disabled="isAnimating || full" @click="addStart">+ в начало</button>
    <button class="btn-action" :disabled="isAnimating || full" @click="addEnd">+ в конец</button>
    <button class="btn-action" :disabled="isAnimating || full" @click="addMiddle">+ в середину</button>
    <button class="btn-action" :disabled="isAnimating || empty" @click="removeFirst">− первую</button>
    <button class="btn-action" :disabled="isAnimating || empty" @click="removeLast">− последнюю</button>
    <span class="card-counter">{{ cards.length }} / {{ MAX_CARDS }} карточек</span>
  </div>

  <div class="card-grid">
    <div
      v-for="card in cards"
      :key="card.id"
      ref="cardEls"
      class="card"
      :style="{ '--card-color': card.color }"
    >
      <span class="card__title">{{ card.title }}</span>
      <span class="card__id">#{{ card.id }}</span>
    </div>
  </div>
</template>

<script setup lang="ts">
import { ref, computed, nextTick, useTemplateRef } from 'vue';
import { useCardAnimation } from '../../src/vue';

interface Card {
  id: number;
  title: string;
  color: string;
}

const COLORS = ['#ef4444', '#f97316', '#eab308', '#22c55e', '#3b82f6', '#a855f7', '#ec4899', '#14b8a6'];
const LABELS = ['Alpha', 'Beta', 'Gamma', 'Delta', 'Epsilon', 'Zeta', 'Eta', 'Theta'];
const MAX_CARDS = 12;

let nextId = 5;
function newCard(): Card {
  const idx = nextId % COLORS.length;
  return { id: nextId++, title: `Карточка ${LABELS[idx] ?? String(nextId)}`, color: COLORS[idx] ?? '#6366f1' };
}

const cards = ref<Card[]>([
  { id: 1, title: 'Карточка Alpha', color: COLORS[0] },
  { id: 2, title: 'Карточка Beta', color: COLORS[1] },
  { id: 3, title: 'Карточка Gamma', color: COLORS[2] },
  { id: 4, title: 'Карточка Delta', color: COLORS[3] },
]);

const full = computed(() => cards.value.length >= MAX_CARDS);
const empty = computed(() => cards.value.length === 0);

const cardEls = useTemplateRef<HTMLElement[]>('cardEls');
const { snapshot, animateMove, isAnimating } = useCardAnimation({ duration: 400, stagger: 25 });

async function triggerChange(updater: () => void): Promise<void> {
  snapshot(cardEls.value ?? []);
  updater();
  await nextTick();
  await animateMove(cardEls.value ?? []);
}

function addStart(): void { void triggerChange(() => { cards.value = [newCard(), ...cards.value]; }); }
function addEnd(): void { void triggerChange(() => { cards.value = [...cards.value, newCard()]; }); }
function addMiddle(): void {
  void triggerChange(() => {
    const mid = Math.floor(cards.value.length / 2);
    cards.value = [...cards.value.slice(0, mid), newCard(), ...cards.value.slice(mid)];
  });
}
function removeFirst(): void { void triggerChange(() => { cards.value = cards.value.slice(1); }); }
function removeLast(): void { void triggerChange(() => { cards.value = cards.value.slice(0, -1); }); }
</script>
